/* eslint-disable react/jsx-props-no-spreading */
import type {AppProps} from 'next/app'
import '../styles/globals.css'
import Head from 'next/head'
import Navbar from '../../components/Navbar/Navbar'
import Footer from '../../components/Layout/Footer'
import {Provider} from 'react-redux'
import {store} from '../../store'
import Alerts from '../../components/Alerts/Alerts'
import {useEffect} from 'react'
import {loadUser} from '../../actions/auth'
import {QueryClient, QueryClientProvider} from 'react-query'
import {ReactQueryDevtools} from 'react-query/devtools'
import {withTRPC} from '@trpc/next'
import type {AppRouter} from '../server/router'
import {AppType} from 'next/dist/shared/lib/utils'

const MyApp: AppType = ({Component, pageProps}) => {
  useEffect(() => {
    store.dispatch(loadUser())
  })
  const queryClient = new QueryClient()
  return (
    <QueryClientProvider client={queryClient}>
      <ReactQueryDevtools initialIsOpen={false} />
      <Provider store={store}>
        <Head>
          <title>Vinyl Mania</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Alerts />
        <div id="modal"></div>
        <Component {...pageProps} />
        <Footer />
      </Provider>
    </QueryClientProvider>
  )
}

export default withTRPC<AppRouter>({
  config({ctx}) {
    /**
     * If you want to use SSR, you need to use the server's full URL
     * @link https://trpc.io/docs/ssr
     */
    const url = process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}/api/trpc`
      : 'http://localhost:3000/api/trpc'

    return {
      url,
      /**
       * @link https://react-query.tanstack.com/reference/QueryClient
       */
      // queryClientConfig: { defaultOptions: { queries: { staleTime: 60 } } },
    }
  },
  /**
   * @link https://trpc.io/docs/ssr
   */
  ssr: false,
})(MyApp)
