/* eslint-disable react/jsx-props-no-spreading */
import type {AppProps} from 'next/app'
import '../styles/globals.css'
import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import Footer from '../components/Layout/Footer'
import {Provider} from 'react-redux'
import {store} from '../store'
import Alerts from '../components/Alerts/Alerts'
import {useEffect} from 'react'
import {loadUser} from '../actions/auth'

const MyApp: React.FC<AppProps> = ({Component, pageProps}) => {
  useEffect(() => {
    store.dispatch(loadUser())
  })
  return (
    <Provider store={store}>
      <Head>
        <title>Vinyl Mania</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Alerts />
      <div id="modal"></div>
      <Component {...pageProps} />
      <Footer />
    </Provider>
  )
}

export default MyApp
