/* eslint-disable react/jsx-props-no-spreading */
import type {AppProps} from 'next/app'
import '../styles/globals.css'
import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import Footer from '../components/Footer/Footer'

const MyApp: React.FC<AppProps> = ({Component, pageProps}) => (
  <>
    <Head>
      <title>Vinyl Mania</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    <Component {...pageProps} />
    <Footer />
  </>
)

export default MyApp
